<a href="https://colab.research.google.com/github/Navanithapatel/AD/blob/main/pythonday11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
k=[4,2.56789,9,87.9999,40,'hyderabad']
k

[4, 2.56789, 9, 87.9999, 40, 'hyderabad']

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns


In [ ]:
k=[4,2,9,87.9999,40]
k

[4, 2, 9, 87.9999, 40]

In [ ]:
pd.Series(k)

0     4.0000
1     2.0000
2     9.0000
3    87.9999
4    40.0000
dtype: float64

In [ ]:
a=np.random.randint(20,50,(5,4))
a

array([[32, 41, 38, 38],
       [40, 37, 41, 45],
       [47, 43, 38, 43],
       [31, 22, 39, 31],
       [23, 43, 29, 42]])

In [ ]:
a.ndim

1

In [ ]:
a=np.random.randint(20,50,(5,4))
a

array([[29, 27, 21, 21],
       [28, 43, 20, 32],
       [21, 36, 47, 47],
       [23, 36, 43, 35],
       [27, 20, 48, 29]])

In [ ]:
pd.Series(a)

ValueError: Data must be 1-dimensional, got ndarray of shape (5, 4) instead

In [ ]:
a=np.random.randint(20,50,15)
a

array([21, 39, 43, 23, 48, 26, 28, 37, 27, 21, 32, 21, 49, 28, 30])

In [ ]:
pd.Series(a)

0     21
1     39
2     43
3     23
4     48
5     26
6     28
7     37
8     27
9     21
10    32
11    21
12    49
13    28
14    30
dtype: int64

In [ ]:
a[5]

26

In [ ]:
np.random.seed(34)#seed is used to get same numbers / matrices
b=np.random.randint(100,200,(6,5))
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [ ]:
b.ndim

2

In [ ]:
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [39]:
df=pd.DataFrame(b)
df

0    1    2    3    4
0  133  185  168  135  169
1  111  178  129  118  129
2  189  129  120  196  162
3  105  120  151  119  185
4  121  163  172  142  184
5  172  177  136  102  137

In [43]:
df=pd.DataFrame(b,columns=['Roll','Name','Age','Id','Country'])
df

Roll  Name  Age   Id  Country
0   133   185  168  135      169
1   111   178  129  118      129
2   189   129  120  196      162
3   105   120  151  119      185
4   121   163  172  142      184
5   172   177  136  102      137

In [45]:
df=pd.DataFrame(b,columns=['Roll','Name','Age','Id','Country'],index=[11,12,13,14,15,16])
df

Roll  Name  Age   Id  Country
11   133   185  168  135      169
12   111   178  129  118      129
13   189   129  120  196      162
14   105   120  151  119      185
15   121   163  172  142      184
16   172   177  136  102      137

In [46]:
df.iloc[0,0:3]

Roll    133
Name    185
Age     168
Name: 11, dtype: int64

In [47]:
df.iloc[0,[0,1,2]]

Roll    133
Name    185
Age     168
Name: 11, dtype: int64

In [49]:
df.iloc[[0,5]]

Roll  Name  Age   Id  Country
11   133   185  168  135      169
16   172   177  136  102      137

In [50]:
df.iloc[1,3,4]

IndexingError: Too many indexers

In [53]:
df.loc[[11,12,13]]

Roll  Name  Age   Id  Country
11   133   185  168  135      169
12   111   178  129  118      129
13   189   129  120  196      162

In [55]:
df['Age']

11    168
12    129
13    120
14    151
15    172
16    136
Name: Age, dtype: int64

In [57]:
df[['Age','Country']]

Age  Country
11  168      169
12  129      129
13  120      162
14  151      185
15  172      184
16  136      137

In [60]:
df.loc[[11,12,13],['Name','Age','Country']]

Name  Age  Country
11   185  168      169
12   178  129      129
13   129  120      162

In [61]:
#sns.load_dataset('')
sns.get_dataset_names

<function seaborn.utils.get_dataset_names()>

In [64]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [65]:
df.shape

(244, 7)

In [66]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [67]:
df.shape

(244, 7)

In [68]:
type(df)

pandas.core.frame.DataFrame

In [69]:
df.shape

(244, 7)