<a href="https://colab.research.google.com/github/Navanithapatel/AD/blob/main/pythonday16_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
from scipy.stats import zscore
data=sns.load_dataset('iris')
df=data.copy()
z_scores = np.abs(zscore(df.drop('species',axis=1)))

In [6]:
z_scores

sepal_length  sepal_width  petal_length  petal_width
0        0.900681     1.019004      1.340227     1.315444
1        1.143017     0.131979      1.340227     1.315444
2        1.385353     0.328414      1.397064     1.315444
3        1.506521     0.098217      1.283389     1.315444
4        1.021849     1.249201      1.340227     1.315444
..            ...          ...           ...          ...
145      1.038005     0.131979      0.819596     1.448832
146      0.553333     1.282963      0.705921     0.922303
147      0.795669     0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662     0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [9]:
zscore(df.drop('species',axis=1))

sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.019004     -1.340227    -1.315444
1       -1.143017    -0.131979     -1.340227    -1.315444
2       -1.385353     0.328414     -1.397064    -1.315444
3       -1.506521     0.098217     -1.283389    -1.315444
4       -1.021849     1.249201     -1.340227    -1.315444
..            ...          ...           ...          ...
145      1.038005    -0.131979      0.819596     1.448832
146      0.553333    -1.282963      0.705921     0.922303
147      0.795669    -0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662    -0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [14]:
z_scores.loc[10:15]

sepal_length  sepal_width  petal_length  petal_width
10      0.537178     1.479398      1.283389     1.315444
11      1.264185     0.788808      1.226552     1.315444
12      1.264185     0.131979      1.340227     1.447076
13      1.870024     0.131979      1.510739     1.447076
14      0.052506     2.169988      1.453901     1.315444
15      0.173674     3.090775      1.283389     1.052180

In [10]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:


threshold = 3
non_outliers = (z_scores < threshold).all(axis=1)

df_no_outliers = df[non_outliers]



In [16]:
df_no_outliers

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [19]:
threshold = 3
outliers = (z_scores > threshold)

outlier_rows = df[outliers.any(axis=1)]
outlier_rows



sepal_length  sepal_width  petal_length  petal_width species
15           5.7          4.4           1.5          0.4  setosa

In [20]:
from sklearn.ensemble import IsolationForest
import seaborn as sns
import pandas as pd
import numpy as np

In [21]:
data = sns.load_dataset('iris')
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [23]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data['species']=lb.fit_transform(data['species'])

In [24]:
clf = IsolationForest(random_state=10,contamination=0.1)
clf.fit(data)

IsolationForest(contamination=0.1, random_state=10)

In [32]:
y_pred_outliers = clf.predict(data)
idx=np.where(y_pred_outliers==-1)
idx[0]

array([ 13,  14,  15,  18,  22,  32,  33,  41,  60, 100, 106, 109, 117,
       118, 131])

In [28]:
clf.predict(data)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,
        1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [30]:
y_pred_outliers=clf.predict(data)

In [31]:
y_pred_outliers==-1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False,