<a href="https://colab.research.google.com/github/Navanithapatel/AD/blob/main/pythonday7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(20,60,15)

In [ ]:
a

array([53, 27, 24, 59, 31, 23, 50, 51, 54, 49, 34, 50, 22, 24, 42])

In [ ]:
a[-9]

50

In [ ]:
a[-2:-9:-1]

array([24, 22, 50, 34, 49, 54, 51])

In [ ]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b


array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
b[3]

array([46, 45, 52, 74, 65, 53, 60, 55])

In [ ]:
b[6]

array([75, 54, 74, 69, 54, 64, 52, 61])

In [ ]:
b[6,4]

54

In [ ]:
b[3,6]

60

In [ ]:
b[1:5]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51]])

In [ ]:
b[1:5,1:5]

array([[59, 55, 77, 69],
       [56, 51, 58, 59],
       [45, 52, 74, 65],
       [72, 46, 69, 65]])

In [ ]:
array[row_start:row-end:row-step,col_start:col_end:col_step]

In [ ]:
b[1:7,1:7]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [ ]:
b[:,6]

array([61, 48, 68, 60, 75, 67, 52])

In [ ]:
b[2,1]

56

In [ ]:
b[0:3,0:7]

array([[63, 45, 48, 67, 74, 64, 61],
       [61, 59, 55, 77, 69, 69, 48],
       [71, 56, 51, 58, 59, 47, 68]])

In [ ]:
np.where(b>40)b

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
        5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
        6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3,
        4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7]))

In [ ]:
np.where(a<30)

(array([ 1,  2,  5, 12, 13]),)

In [ ]:
a[a<30]

array([27, 24, 23, 22, 24])

In [ ]:
a

array([53, 27, 24, 59, 31, 23, 50, 51, 54, 49, 34, 50, 22, 24, 42])